-- VHDL Entity multi_LIB.bitadder.symbol
--
-- Created:
--          by - mg255.bin (cparch11.ecn.purdue.edu)
--          at - 12:37:36 11/01/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.2a (Build 7)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY bitadder IS
   PORT( 
      CIN    : IN     std_logic;
      A1     : IN     std_logic;
      B1     : IN     std_logic;   -- carry in , a , b
      bitOut : OUT    std_logic;
      COUT   : OUT    std_logic
   );

-- Declarations

END bitadder ;

--
-- VHDL Architecture multi_LIB.bitadder.dataflow_Adder
--
-- Created:
--          by - mg255.bin (cparch11.ecn.purdue.edu)
--          at - 12:37:36 11/01/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.2a (Build 7)
--



ARCHITECTURE dataflow_Adder OF bitadder IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   cout <= (A1 and B1) or (a1 and CIN) or (b1 and CIN);
   bitOut <= A1 xor B1 xor CIN;


   -- Instance port mappings.

END dataflow_Adder;
