Date:Fri Oct 28 03:50:15 PM EDT 2011
Input command file generated by LEDA

#VERILOGCompiler	/package/eda/synopsys/leda-E-2010.12/amd64/bin/ve -M +no_lvs_env -c -z -p2 -i -k95e -log /home/ecegrid/a/mg255/ece437/project3/leda-logs/compiler.log -full_log -snote +max_case+8 +max_casexz+8 -maxviolations 100 -top MYCPU -save_uniquified_modules
#VHDLCompiler	/package/eda/synopsys/leda-E-2010.12/amd64/bin/v -M +no_lvs_env  -c -z -i -k93e -log /home/ecegrid/a/mg255/ece437/project3/leda-logs/compiler.log -full_log -snote -maxviolations 100
#HOMELESS	LEDA_WORK
#Makefile-Name	LEDA_Makefile
#Makelibs-Name	LEDA_Makelibs
#Project-Name	/home/ecegrid/a/mg255/ece437/project3/leda.pro

#VHDLSuffixes
#End

#VHDLSuffixes
#End

#VERILOGSuffixes
#End
#Mappings
#End
#Files LEDA_WORK
#End

#VERILOGSuffixes
#End

#VHDLSuffixes
vhd -
vhdl -
#End
#Mappings
#End
#Files LEDA_WORK
   /home/ecegrid/a/mg255/ece437/project3/source/Add32.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/AluCont.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/CLU.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/DataRtn.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/Decode.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/EXMEM_REG.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/FwdUnit.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/IDEX_REG.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/IFID_REG.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/J_JAL.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/MEMWB_REG.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/MemCont.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/PcBlock.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/ShiftXtd.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/alu.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/bitAdder.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/data16x184.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/dcache.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/icache.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/icache_ctrl.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/mycpu.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/registerFile.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/dCacheCLU.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/dCacheCLU.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/dCacheCLU.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/dCacheCLU.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/dCacheCLU.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/icache.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/dCacheCLU.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/icache.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/dCacheCLU.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/dCacheCLU.vhd
   /home/ecegrid/a/mg255/ece437/project3/source/dCacheCLU.vhd
#End
#Resources
   IEEE $LEDA_PATH/amd64/resources/resource_93/IEEE 
   SNPS_EXT $LEDA_PATH/amd64/resources/resource_93/SNPS_EXT 
   STD $LEDA_PATH/amd64/resources/resource_93/STD 
   SYNOPSYS $LEDA_PATH/amd64/resources/resource_93/SYNOPSYS 
#End
